apiVersion: v1
kind: Pod
metadata:
  name: my-data-pod-2
  namespace: playground
spec:
  containers:
  - name: web-app
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html/data
      name: persistent-storage
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: my-app-claim
