apiVersion: v1
kind: Pod
metadata:
  name: data-writer
  namespace: playground
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - 'echo "Data written on $(date)" >> /mnt/data/test.txt; sleep 3600'
    volumeMounts:
    - mountPath: /mnt/data
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-claim
