apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-claim
  namespace: playground
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
